<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class WeeklyActivitiesSeeder extends Seeder
{
    public function run(): void
    {
        // Verifica se já existem registros na tabela 'weekly_activities'
        $quantidade = $this->db->table('weekly_activities')->countAllResults();

        // Só insere se a tabela estiver vazia (quantidade == 0)
        if ($quantidade == 0) {
            $now = date('Y-m-d H:i:s');

            $this->db->table('weekly_activities')->insertBatch([
                [
                    'theme_behavioral_questions_id' => 1,
                    'objective' => 'Substituir o consumo passivo do feed infinito por atividades ativas e intencionais.',
                    'task' => 'Leitura Contínua: Ler 10 páginas de um livro físico sem interrupções.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 1,
                    'objective' => 'Substituir o consumo passivo do feed infinito por atividades ativas e intencionais.',
                    'task' => 'Alongamento Guiado: Substituir 15 minutos de scroll por um alongamento de corpo inteiro.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                
                [
                    'theme_behavioral_questions_id' => 1,
                    'objective' => 'Substituir o consumo passivo do feed infinito por atividades ativas e intencionais.',
                    'task' => 'Rabiscos Livres (Doodle): Desenhar ou rabiscar livremente em um papel por 10 minutos para esvaziar a mente.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 1,
                    'objective' => 'Substituir o consumo passivo do feed infinito por atividades ativas e intencionais.',
                    'task' => 'Leitura Profunda: Ler um artigo longo (long-form) sobre um tema de interesse, sem clicar em hiperlinks paralelos.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 1,
                    'objective' => 'Substituir o consumo passivo do feed infinito por atividades ativas e intencionais.',
                    'task' => 'Organização Rápida: Organizar a mesa de trabalho ou uma gaveta por 15 minutos.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 1,
                    'objective' => 'Substituir o consumo passivo do feed infinito por atividades ativas e intencionais.',
                    'task' => 'Quebra-Cabeça (de preferência físico): Montar um quebra-cabeça, cubo mágico ou jogar Sudoku em papel por 10 minutos.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 1,
                    'objective' => 'Substituir o consumo passivo do feed infinito por atividades ativas e intencionais.',
                    'task' => 'Escrita de Metas: Escrever os objetivos do dia em um bloco de notas físico, longe de qualquer tela.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 1,
                    'objective' => 'Substituir o consumo passivo do feed infinito por atividades ativas e intencionais.',
                    'task' => 'Café Consciente: Trocar o scroll matinal por preparar e tomar o café da manhã em total silêncio.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 1,
                    'objective' => 'Substituir o consumo passivo do feed infinito por atividades ativas e intencionais.',
                    'task' => 'Caminhada Desconectada: Fazer uma caminhada de 10 minutos sem levar o celular ou usar fones de ouvido.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 1,
                    'objective' => 'Substituir o consumo passivo do feed infinito por atividades ativas e intencionais.',
                    'task' => 'Hobby Manual: Dedicar 15 minutos a uma atividade manual (ex: origami, tricô, montar blocos, tocar um instrumento).',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 2,
                    'objective' => 'Desativar alertas e treinar a concentração imersiva.',
                    'task' => 'Imersão "Não Perturbe": Trabalhar ou estudar por 1 hora com o celular configurado no modo "Não Perturbe".',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 2,
                    'objective' => 'Desativar alertas e treinar a concentração imersiva.',
                    'task' => 'Limpeza Visual: Desativar permanentemente os alertas visuais (balões e números) da rede social mais utilizada.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 2,
                    'objective' => 'Desativar alertas e treinar a concentração imersiva.',
                    'task' => 'Isolamento Físico: Deixar o aparelho em outro cômodo fechado durante o horário de almoço ou jantar.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 2,
                    'objective' => 'Desativar alertas e treinar a concentração imersiva.',
                    'task' => 'Notificações em Lote: Configurar o sistema do celular para entregar notificações agrupadas apenas em dois horários (ex: 12h e 18h).',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 2,
                    'objective' => 'Desativar alertas e treinar a concentração imersiva.',
                    'task' => 'Pomodoro Silencioso: Realizar uma tarefa complexa usando a técnica Pomodoro (ex: 45 min), com o aparelho na gaveta.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 2,
                    'objective' => 'Desativar alertas e treinar a concentração imersiva.',
                    'task' => 'Silêncio Seletivo: Silenciar por tempo indeterminado todos os grupos de mensagens que não sejam estritamente urgentes.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 2,
                    'objective' => 'Desativar alertas e treinar a concentração imersiva.',
                    'task' => 'Entretenimento Focado: Assistir a um episódio de série ou a um filme deixando o celular em outro cômodo.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 2,
                    'objective' => 'Desativar alertas e treinar a concentração imersiva.',
                    'task' => 'Amanhecer Desconectado: Passar a primeira hora inteira após acordar sem conferir a barra de notificações.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 2,
                    'objective' => 'Desativar alertas e treinar a concentração imersiva.',
                    'task' => 'Fim da Vibração: Desativar a vibração e o som para qualquer aplicativo que não seja de chamadas telefônicas essenciais.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 2,
                    'objective' => 'Desativar alertas e treinar a concentração imersiva.',
                    'task' => 'Jejum Digital: Realizar um "jejum de notificações" rigoroso de 4 horas durante o fim de semana.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 3,
                    'objective' => 'Regulação da Atenção Plena e combate ao medo de exclusão virtual.',
                    'task' => 'Escaneamento Corporal: Praticar 10 minutos de Body Scan (rastreamento de sensações no corpo) ao acordar.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 3,
                    'objective' => 'Regulação da Atenção Plena e combate ao medo de exclusão virtual.',
                    'task' => 'Sábado Offline: Passar um período de 4 horas no fim de semana totalmente desconectado da internet.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 3,
                    'objective' => 'Regulação da Atenção Plena e combate ao medo de exclusão virtual.',
                    'task' => 'Diário de Gratidão: Listar 3 eventos vividos no dia real pelos quais é grato, reforçando o valor do momento presente.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 3,
                    'objective' => 'Regulação da Atenção Plena e combate ao medo de exclusão virtual.',
                    'task' => 'Respiração Coerente: Praticar 15 minutos de respiração diafragmática para equilibrar o sistema nervoso.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 3,
                    'objective' => 'Regulação da Atenção Plena e combate ao medo de exclusão virtual.',
                    'task' => 'Observação Passiva: Ir a um local público (café, praça) e observar o ambiente por 10 minutos, sem tocar no celular.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 3,
                    'objective' => 'Regulação da Atenção Plena e combate ao medo de exclusão virtual.',
                    'task' => 'Refeição Consciente: Fazer uma refeição prestando atenção exclusiva aos sabores e texturas (mindful eating).',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 3,
                    'objective' => 'Regulação da Atenção Plena e combate ao medo de exclusão virtual.',
                    'task' => 'Desinstalação Estratégica: Deletar temporariamente (por 3 dias) o aplicativo que mais causa a sensação de "ficar de fora".',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 3,
                    'objective' => 'Regulação da Atenção Plena e combate ao medo de exclusão virtual.',
                    'task' => 'Meditação de Aceitação: Reconhecer o sentimento de FoMO quando ele surgir, observá-lo sem julgamentos e deixá-lo ir.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 3,
                    'objective' => 'Regulação da Atenção Plena e combate ao medo de exclusão virtual.',
                    'task' => 'Registro de Autocontrole: Anotar em um caderno todas as vezes em que sentiu o impulso de checar a vida alheia e escolheu não fazê-lo.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 3,
                    'objective' => 'Regulação da Atenção Plena e combate ao medo de exclusão virtual.',
                    'task' => 'Dinâmica da Árvore: Realizar a "Meditação da Árvore" por 10 minutos, visualizando enraizamento e resiliência frente às mudanças.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 4,
                    'objective' => 'Reestruturação do foco prolongado e recuperação da clareza mental.',
                    'task' => 'Escuta Ativa: Ouvir um podcast educativo ou aula em áudio de 30 minutos sem fazer nada visualmente estimulante.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 4,
                    'objective' => 'Reestruturação do foco prolongado e recuperação da clareza mental.',
                    'task' => 'Imersão Documental: Assistir a um documentário de 1 hora prestando atenção exclusiva à narrativa.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 4,
                    'objective' => 'Reestruturação do foco prolongado e recuperação da clareza mental.',
                    'task' => 'Micro-Aprendizado: Dedicar 15 minutos para estudar intensamente um novo idioma ou conceito teórico complexo.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 4,
                    'objective' => 'Reestruturação do foco prolongado e recuperação da clareza mental.',
                    'task' => 'Desafio de Lógica: Resolver um jogo focado em cognição (xadrez, palavras-cruzadas complexas) no formato físico.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 4,
                    'objective' => 'Reestruturação do foco prolongado e recuperação da clareza mental.',
                    'task' => 'Leitura Densa: Ler um capítulo de um livro de ficção ou filosofia que exija imaginação e raciocínio encadeado.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 4,
                    'objective' => 'Reestruturação do foco prolongado e recuperação da clareza mental.',
                    'task' => 'Escrita Discursiva: Escrever um texto contínuo de 1 página sobre um assunto que você domina.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 4,
                    'objective' => 'Reestruturação do foco prolongado e recuperação da clareza mental.',
                    'task' => 'Reprodução Prática: Assistir a um tutorial longo (marcenaria, culinária, arte) e replicá-lo na prática imediatamente.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 4,
                    'objective' => 'Reestruturação do foco prolongado e recuperação da clareza mental.',
                    'task' => 'Atenção Sustentada: Manter o foco visual fixo em um único objeto estático no ambiente por 3 minutos ininterruptos.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 4,
                    'objective' => 'Reestruturação do foco prolongado e recuperação da clareza mental.',
                    'task' => 'Mapeamento Mental: Criar um mapa mental no papel conectando as ideias de um projeto em andamento.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 4,
                    'objective' => 'Reestruturação do foco prolongado e recuperação da clareza mental.',
                    'task' => 'Anotações Focadas: Assistir a uma palestra online e fazer anotações à mão, treinando a síntese de informações.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 5,
                    'objective' => 'Reduzir a imprevisibilidade de recompensas e a busca por validação externa',
                    'task' => 'Postagem Fantasma: Postar uma foto ou ideia em uma rede e desativar/deslogar do aplicativo pelas próximas 24 horas.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 5,
                    'objective' => 'Reduzir a imprevisibilidade de recompensas e a busca por validação externa',
                    'task' => 'Elogio Privado: Escrever um elogio sincero a si mesmo em um diário, sem compartilhar com ninguém.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 5,
                    'objective' => 'Reduzir a imprevisibilidade de recompensas e a busca por validação externa',
                    'task' => 'Vitória Silenciosa: Concluir uma atividade da qual se orgulha muito e não registrá-la em foto ou vídeo.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 5,
                    'objective' => 'Reduzir a imprevisibilidade de recompensas e a busca por validação externa',
                    'task' => 'Métricas Ocultas: Utilizar ferramentas da própria rede social (se disponíveis) para ocultar o número de curtidas do seu perfil.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 5,
                    'objective' => 'Reduzir a imprevisibilidade de recompensas e a busca por validação externa',
                    'task' => 'Celebração Interna: Comemorar uma pequena vitória do dia meditando por 5 minutos sobre a sensação de dever cumprido.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 5,
                    'objective' => 'Reduzir a imprevisibilidade de recompensas e a busca por validação externa',
                    'task' => 'Validação Direta: Enviar uma mensagem privada e direta elogiando alguém, em vez de fazer um comentário público.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 5,
                    'objective' => 'Reduzir a imprevisibilidade de recompensas e a busca por validação externa',
                    'task' => 'Observador Passivo: Consumir conteúdo online por 30 minutos com a regra estrita de não curtir ou comentar em nada.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 5,
                    'objective' => 'Reduzir a imprevisibilidade de recompensas e a busca por validação externa',
                    'task' => 'TBT Pessoal: Revisar fotos antigas no rolo da câmera para curtir a memória, sem publicá-las na internet.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 5,
                    'objective' => 'Reduzir a imprevisibilidade de recompensas e a busca por validação externa',
                    'task' => 'Mural de Qualidades: Escrever 3 qualidades que você admira em si próprio em post-its e colar no espelho.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 5,
                    'objective' => 'Reduzir a imprevisibilidade de recompensas e a busca por validação externa',
                    'task' => 'Fim de Semana Cego: Passar sábado e domingo inteiros sem abrir a aba de "Métricas", "Atividade" ou "Notificações" de engajamento.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 6,
                    'objective' => 'Terapia de Aceitação e Compromisso e manejo de vazio existencial.',
                    'task' => 'Aceitação do Tédio: Sentar em uma cadeira e apenas observar a sensação física e mental do tédio por 5 minutos, sem reagir.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 6,
                    'objective' => 'Terapia de Aceitação e Compromisso e manejo de vazio existencial.',
                    'task' => 'Substituição Sensorial: Quando sentir vontade de pegar o celular por tédio, levantar e beber um copo de água lentamente.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 6,
                    'objective' => 'Terapia de Aceitação e Compromisso e manejo de vazio existencial.',
                    'task' => 'Dinâmica Largar Peso: Realizar a respiração profunda do "Largar peso", relaxando o corpo e desapegando da necessidade de preencher o vazio.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 6,
                    'objective' => 'Terapia de Aceitação e Compromisso e manejo de vazio existencial.',
                    'task' => 'Ócio Criativo: Reservar uma janela de 30 minutos no dia para absolutamente não fazer nada planejado.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 6,
                    'objective' => 'Terapia de Aceitação e Compromisso e manejo de vazio existencial.',
                    'task' => 'Observação Natural: Olhar pela janela para observar o movimento das nuvens ou o pôr do sol, sem registrar a imagem.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 6,
                    'objective' => 'Terapia de Aceitação e Compromisso e manejo de vazio existencial.',
                    'task' => 'Espera Consciente: Ao aguardar em uma fila ou recepção, manter o celular no bolso e concentrar-se na própria respiração.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 6,
                    'objective' => 'Terapia de Aceitação e Compromisso e manejo de vazio existencial.',
                    'task' => 'Mapeamento de Emoções: Escrever rapidamente em um papel quais sentimentos reais estão escondidos por trás do tédio repentino.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 6,
                    'objective' => 'Terapia de Aceitação e Compromisso e manejo de vazio existencial.',
                    'task' => 'Caminhada Plena: Praticar a caminhada atenta focando unicamente na sensação mecânica e no peso dos pés tocando o solo.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 6,
                    'objective' => 'Terapia de Aceitação e Compromisso e manejo de vazio existencial.',
                    'task' => 'Imersão Auditiva: Ouvir uma música instrumental com os olhos fechados, prestando atenção à separação dos instrumentos.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 6,
                    'objective' => 'Terapia de Aceitação e Compromisso e manejo de vazio existencial.',
                    'task' => 'Reconexão Corporal: Fazer 10 movimentos de alongamento ou Yoga sempre que sentir a mente buscando distração no tédio.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 7,
                    'objective' => 'Psicoterapia Interpessoal Prática e construção de relações não líquidas.',
                    'task' => 'Voz sobre Texto: Ligar para um familiar ou amigo próximo para uma conversa de 15 minutos, substituindo mensagens de texto.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 7,
                    'objective' => 'Psicoterapia Interpessoal Prática e construção de relações não líquidas.',
                    'task' => 'Encontro Real: Propor um café ou almoço estritamente presencial com um colega ou amigo.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 7,
                    'objective' => 'Psicoterapia Interpessoal Prática e construção de relações não líquidas.',
                    'task' => 'Atividade Coletiva Offline: Fazer uma atividade em grupo (jogo de tabuleiro, cozinhar) onde os celulares ficam retidos em uma caixa.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 7,
                    'objective' => 'Psicoterapia Interpessoal Prática e construção de relações não líquidas.',
                    'task' => 'Escuta Empática: Perguntar sobre o dia de alguém e escutar ativamente, prestando atenção plena sem interromper ou preparar uma resposta.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 7,
                    'objective' => 'Psicoterapia Interpessoal Prática e construção de relações não líquidas.',
                    'task' => 'Mensagem Tátil: Escrever uma carta ou bilhete físico e entregar em mãos para alguém importante.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 7,
                    'objective' => 'Psicoterapia Interpessoal Prática e construção de relações não líquidas.',
                    'task' => 'Contato Visual: Durante qualquer interação presencial hoje, manter contato visual direto e guardar o telefone no bolso.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 7,
                    'objective' => 'Psicoterapia Interpessoal Prática e construção de relações não líquidas.',
                    'task' => 'Comunidade Local: Participar presencialmente de uma aula, workshop ou prática de esporte coletivo na comunidade.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 7,
                    'objective' => 'Psicoterapia Interpessoal Prática e construção de relações não líquidas.',
                    'task' => 'Reconhecimento Verbal: Fazer um elogio sincero e presencial para três pessoas diferentes no ambiente de trabalho ou estudo.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 7,
                    'objective' => 'Psicoterapia Interpessoal Prática e construção de relações não líquidas.',
                    'task' => 'Meditação Loving-kindness: Praticar a meditação de "Amor Benevolente", direcionando pensamentos de paz e segurança a conhecidos e desconhecidos.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 7,
                    'objective' => 'Psicoterapia Interpessoal Prática e construção de relações não líquidas.',
                    'task' => 'Santuário Familiar: Organizar um momento "livre de telas" na sala de casa com os moradores por pelo menos 2 horas à noite.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 8,
                    'objective' => 'Criação de atrito digital para barrar o condicionamento automático e impulsivo',
                    'task' => 'Escala de Cinza: Configurar a tela do smartphone para preto e branco, reduzindo o apelo visual e a liberação de dopamina.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 8,
                    'objective' => 'Criação de atrito digital para barrar o condicionamento automático e impulsivo',
                    'task' => 'Ocultação de Gatilhos: Mover o aplicativo que mais drena seu tempo para uma pasta oculta ou para a última tela do aparelho.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 8,
                    'objective' => 'Criação de atrito digital para barrar o condicionamento automático e impulsivo',
                    'task' => 'Barreira Tátil: Enrolar um elástico de dinheiro ao redor do celular; a textura forçará você a pensar antes de desbloquear a tela.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 8,
                    'objective' => 'Criação de atrito digital para barrar o condicionamento automático e impulsivo',
                    'task' => 'Bloqueio Automático: Instalar um aplicativo de bloqueio (ex: Forest) e configurá-lo para impedir acessos durante o horário de trabalho.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 8,
                    'objective' => 'Criação de atrito digital para barrar o condicionamento automático e impulsivo',
                    'task' => 'Regra dos 10 Segundos: Ao sentir o impulso de abrir uma rede social, contar lentamente até 10 antes de tocar na tela.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 8,
                    'objective' => 'Criação de atrito digital para barrar o condicionamento automático e impulsivo',
                    'task' => 'Acesso Dificultado: Apagar o aplicativo principal e forçar-se a acessá-lo apenas pelo navegador de internet do celular.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 8,
                    'objective' => 'Criação de atrito digital para barrar o condicionamento automático e impulsivo',
                    'task' => 'Substituição de Atalho: Trocar a posição do ícone da rede social pelo ícone de um aplicativo de meditação ou leitura.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 8,
                    'objective' => 'Criação de atrito digital para barrar o condicionamento automático e impulsivo',
                    'task' => 'Logoff Obrigatório: Fazer logoff (sair da conta) manualmente todas as vezes que terminar de checar o aplicativo.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 8,
                    'objective' => 'Criação de atrito digital para barrar o condicionamento automático e impulsivo',
                    'task' => 'Deslocamento de Carga: Colocar o carregador de bateria em um cômodo de passagem (como a cozinha), nunca perto da cama ou sofá.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 8,
                    'objective' => 'Criação de atrito digital para barrar o condicionamento automático e impulsivo',
                    'task' => 'Senha Complexa: Desativar a biometria/reconhecimento facial e definir uma senha alfanumérica longa para desbloquear a tela.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 9,
                    'objective' => 'Reestruturação cognitiva e alinhamento de expectativas reais.',
                    'task' => 'Limpeza de Feed: Deixar de seguir ou silenciar 5 perfis que promovem padrões estéticos, financeiros ou de rotina irreais.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 9,
                    'objective' => 'Reestruturação cognitiva e alinhamento de expectativas reais.',
                    'task' => 'Gratidão Imperfeita: Registrar no diário 3 coisas do cotidiano que não são "instagramáveis" (imperfeitas), mas que trazem satisfação genuína.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 9,
                    'objective' => 'Reestruturação cognitiva e alinhamento de expectativas reais.',
                    'task' => 'Algoritmo Saudável: Começar a seguir 3 perfis novos focados exclusivamente em natureza, arte ou educação, alterando as sugestões do sistema.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 9,
                    'objective' => 'Reestruturação cognitiva e alinhamento de expectativas reais.',
                    'task' => 'Autoaceitação: Tirar uma foto do próprio rosto sem nenhum tipo de filtro, não publicar e apenas observar a realidade com gentileza.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 9,
                    'objective' => 'Reestruturação cognitiva e alinhamento de expectativas reais.',
                    'task' => 'Inventário de Habilidades: Listar no papel 5 capacidades e qualidades práticas que você possui no mundo físico.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 9,
                    'objective' => 'Reestruturação cognitiva e alinhamento de expectativas reais.',
                    'task' => 'Organização Material: Dedicar 20 minutos para organizar fisicamente um ambiente da sua casa, conectando-se à realidade tátil.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 9,
                    'objective' => 'Reestruturação cognitiva e alinhamento de expectativas reais.',
                    'task' => 'Dinâmica Estrela de Valores: Identificar e desenhar seus 6 principais valores de vida na "Estrela de Valores", centrando suas decisões neles.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 9,
                    'objective' => 'Reestruturação cognitiva e alinhamento de expectativas reais.',
                    'task' => 'Vulnerabilidade Compartilhada: Conversar abertamente com uma pessoa de confiança sobre um erro ou fracasso recente.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 9,
                    'objective' => 'Reestruturação cognitiva e alinhamento de expectativas reais.',
                    'task' => 'Reset Digital: Limpar o histórico de buscas e cache da rede social para zerar a entrega de anúncios baseados em vidas performatizadas.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 9,
                    'objective' => 'Reestruturação cognitiva e alinhamento de expectativas reais.',
                    'task' => 'Estado Mindfulness: Realizar a prática de alinhamento postural (firmeza e flexibilidade), conectando-se ao presente e dizendo: "Acolho o que pode acontecer".',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 10,
                    'objective' => 'Estabelecimento de zonas livres e quebra de hábitos associativos.',
                    'task' => 'Quarto Analógico: Comprar um despertador físico e proibir estritamente a entrada do smartphone no quarto de dormir',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 10,
                    'objective' => 'Estabelecimento de zonas livres e quebra de hábitos associativos.',
                    'task' => 'Banheiro Offline: Não levar o celular para o banheiro sob nenhuma circunstância durante 7 dias.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 10,
                    'objective' => 'Estabelecimento de zonas livres e quebra de hábitos associativos.',
                    'task' => 'Trajeto Presente: Realizar o trajeto diário (casa-trabalho) prestando atenção ativa aos detalhes do percurso, com o celular na mochila.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 10,
                    'objective' => 'Estabelecimento de zonas livres e quebra de hábitos associativos.',
                    'task' => 'Ritual Matinal Protetor: Manter o celular em Modo Avião durante os primeiros 30 minutos após acordar.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 10,
                    'objective' => 'Estabelecimento de zonas livres e quebra de hábitos associativos.',
                    'task' => 'Mesa Limpa: Estabelecer a mesa de jantar como "Zona Proibida para Telas" durante todas as refeições da semana.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 10,
                    'objective' => 'Estabelecimento de zonas livres e quebra de hábitos associativos.',
                    'task' => 'Pausa Focada: Sempre que pausar o trabalho para beber água ou café, focar nos sentidos (temperatura, sabor) em vez de checar a tela.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 10,
                    'objective' => 'Estabelecimento de zonas livres e quebra de hábitos associativos.',
                    'task' => 'Ocultação no Transporte: Guardar o celular no fundo da bolsa ou mochila enquanto estiver utilizando o transporte público.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 10,
                    'objective' => 'Estabelecimento de zonas livres e quebra de hábitos associativos.',
                    'task' => 'Descompressão Noturna: Substituir o uso do celular na hora anterior ao sono por alongamentos leves ou leitura em papel.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 10,
                    'objective' => 'Estabelecimento de zonas livres e quebra de hábitos associativos.',
                    'task' => 'Carro Sem Notificações: Ao dirigir, deixar o celular no porta-luvas ou no porta-malas, em vez do console central.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
                [
                    'theme_behavioral_questions_id' => 10,
                    'objective' => 'Estabelecimento de zonas livres e quebra de hábitos associativos.',
                    'task' => 'Toque de Recolher Digital: Definir e respeitar um "Toque de Recolher": às 21h, desativar o Wi-Fi e os dados móveis até a manhã seguinte.',
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ],
            ]);

            echo "Atividades semanais criadas com sucesso!\n";
        } else {
            echo "Atividades semanais já existem no banco. Pulando Seed...\n";
        }
    }
}